# Generated by Django 5.2.17 on 2026-10-05 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=16)),
                ('batches', models.PositiveIntegerField(default=0)),
                ('patients_written', models.PositiveIntegerField(default=0)),
                ('observations_written', models.PositiveIntegerField(default=0)),
                ('skipped_invalid', models.PositiveIntegerField(default=0)),
                ('skipped_orphans', models.PositiveIntegerField(default=0)),
                ('count_mismatches', models.PositiveIntegerField(default=0)),
                ('http_requests', models.PositiveIntegerField(default=0)),
                ('http_retries', models.PositiveIntegerField(default=0)),
                ('bytes_received', models.PositiveBigIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(max_length=64, unique=True)),
                ('family_name', models.CharField(blank=True, max_length=255)),
                ('given_names', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=16)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField()),
                ('migrated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('code_system', models.CharField(blank=True, max_length=255)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('display', models.TextField(blank=True)),
                ('value_type', models.CharField(choices=[('quantity', 'Quantity'), ('concept', 'Concept'), ('string', 'String'), ('components', 'Components'), ('none', 'None')], max_length=16)),
                ('value_number', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('value_unit', models.CharField(blank=True, max_length=64)),
                ('value_text', models.TextField(blank=True)),
                ('components', models.JSONField(blank=True, null=True)),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('effective_date_only', models.BooleanField(default=False)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField()),
                ('migrated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='migration.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['patient', '-effective_at'], name='obs_patient_effective_idx')],
            },
        ),
    ]
